(function () {
  "use strict";
  const states = ["pending", "processing", "retry_wait", "completed", "blocked", "needs_review"];
  const $ = (id) => document.getElementById(id);
  let jobsPage = 1, incidentsPage = 1, selectedJob = null, detailVersion = 0;
  let jobsController, incidentsController, summaryController, detailController;
  const formatTime = (value) => {
    if (!value) return "Not applicable";
    const date = new Date(value);
    return Number.isNaN(date.valueOf()) ? "Timestamp unavailable" : `${date.toLocaleString("en-CA", { timeZone: "UTC" })} UTC`;
  };
  async function read(url, controller) {
    const timeout = setTimeout(() => controller.abort(), 8000);
    try { const response = await fetch(url, { headers: { Accept: "application/json" }, signal: controller.signal }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.detail || "Read request failed."); return body; } finally { clearTimeout(timeout); }
  }
  function failure(element, prefix, error) { element.className = "operations-status error"; element.textContent = `${prefix} ${error.name === "AbortError" ? "Timed out or was superseded." : error.message || "Unavailable."}`; }
  function execution(parent, reference, url) {
    if (!reference) return;
    const element = url ? document.createElement("a") : document.createElement("span");
    if (url) { element.href = url; element.target = "_blank"; element.rel = "noopener noreferrer"; element.textContent = `n8n execution ${reference}`; } else { element.className = "identifier"; element.textContent = `Execution reference: ${reference}`; }
    parent.append(element);
  }
  async function summary() {
    summaryController?.abort(); const controller = summaryController = new AbortController(); $("summary-status").textContent = "Refreshing current state…";
    try { const data = await read("/api/operations/summary", controller); if (summaryController !== controller) return; const root = $("state-counts"); root.replaceChildren(); states.forEach((state) => { const card = document.createElement("div"), label = document.createElement("span"), count = document.createElement("strong"); label.textContent = state; count.textContent = String(data.job_counts[state] ?? 0); card.append(label, count); root.append(card); }); $("incident-count").textContent = `Open recovery incidents: ${data.open_incident_count}`; $("summary-status").className = "operations-status"; $("summary-status").textContent = `Observed ${formatTime(data.observed_at)}. Separate requests can observe later worker progress.`; } catch (error) { if (summaryController === controller && error.name !== "AbortError") failure($("summary-status"), "Current-state data is unavailable.", error); }
  }
  function jobsUrl() { const p = new URLSearchParams({ page: String(jobsPage), page_size: "25" }), state = $("job-state").value, lookup = $("lookup-id").value.trim(); if (state) p.set("state", state); if (lookup) { p.set("lookup_kind", $("lookup-kind").value); p.set("lookup_id", lookup); } return `/api/operations/jobs?${p}`; }
  function jobCell(row, value, className) { const cell = document.createElement("td"); cell.textContent = value || "—"; if (className) cell.className = className; row.append(cell); return cell; }
  function renderJobs(data) {
    const body = $("jobs-body"); body.replaceChildren();
    if (!data.items.length) { const row = document.createElement("tr"), cell = document.createElement("td"); cell.colSpan = 6; cell.textContent = $("lookup-id").value.trim() ? "No job matches this valid identifier." : "No recorded jobs match these filters."; row.append(cell); body.append(row); }
    data.items.forEach((job) => { const row = document.createElement("tr"); jobCell(row, job.state, `job-state job-state--${job.state}`); const ref = document.createElement("td"), select = document.createElement("button"); select.type = "button"; select.className = "job-select"; select.textContent = job.id; select.addEventListener("click", () => detail(job.id)); ref.className = "identifier"; ref.append(select, document.createElement("br"), document.createTextNode(`submission: ${job.submission_id}`), document.createElement("br"), document.createTextNode(`correlation: ${job.correlation_id}`)); row.append(ref); jobCell(row, formatTime(job.created_at)); jobCell(row, String(job.attempt_count)); jobCell(row, formatTime(job.next_eligible_at)); jobCell(row, job.last_error_class); body.append(row); });
    $("jobs-status").className = "operations-status"; $("jobs-status").textContent = `Filtered total: ${data.total}. Showing ${data.items.length} on page ${data.page}. Observed ${formatTime(data.observed_at)}.`; $("jobs-page").textContent = `Page ${data.page}`; $("jobs-previous").disabled = data.page <= 1; $("jobs-next").disabled = data.page * data.page_size >= data.total;
  }
  async function jobs() { jobsController?.abort(); const controller = jobsController = new AbortController(); $("jobs-status").textContent = "Loading filtered jobs…"; try { const data = await read(jobsUrl(), controller); if (jobsController === controller) renderJobs(data); } catch (error) { if (jobsController === controller && error.name !== "AbortError") { $("jobs-body").replaceChildren(); failure($("jobs-status"), "Jobs could not be read.", error); } } }
  function field(root, label, value) { const item = document.createElement("div"), term = document.createElement("dt"), detail = document.createElement("dd"); term.textContent = label; detail.textContent = value; item.append(term, detail); root.append(item); }
  function incident(incident) { const item = document.createElement("li"), title = document.createElement("strong"), text = document.createElement("span"); title.textContent = `${incident.state}: ${incident.error_class}`; text.textContent = `${incident.linked ? "linked" : "unlinked"} · recorded ${formatTime(incident.created_at)}${incident.resolved_at ? ` · resolved ${formatTime(incident.resolved_at)}` : ""}${incident.failed_node ? ` · node ${incident.failed_node}` : ""}`; item.append(title, text); execution(item, incident.execution_reference, incident.execution_url); return item; }
  function renderDetail(data) {
    const root = $("job-detail"); root.className = "job-detail"; root.replaceChildren(); const fields = document.createElement("dl"); fields.className = "trace-grid";
    [["Job ID", data.id], ["Submission ID", data.submission_id], ["Correlation ID", data.correlation_id], ["Operation", data.operation_kind], ["Current state", data.state], ["Created (UTC)", formatTime(data.created_at)], ["Updated (UTC)", formatTime(data.updated_at)], ["Actual CRM write attempts", String(data.attempt_count)], ["Reconciliation failures", String(data.reconciliation_failure_count)], ["Next eligible retry (UTC)", formatTime(data.next_eligible_at)], ["Last recorded error", [data.last_error_class, data.last_error_message].filter(Boolean).join(": ") || "None"], ["CRM lead", data.completed_lead ? `${data.completed_lead.id} (${data.completed_lead.full_name}; ${data.completed_lead.pipeline_stage})` : "Pending CRM creation"], ["Lease", data.lease_expired_at_observation ? "Recorded lease was expired at observation time" : "No expired recorded lease observed"]].forEach(([label, value]) => field(fields, label, value)); root.append(fields);
    const trace = document.createElement("a"); trace.href = `/index.html?trace=${encodeURIComponent(data.correlation_id)}`; trace.textContent = "Inspect correlation lifecycle trace"; root.append(trace); const source = document.createElement("p"); execution(source, data.source_execution_reference, data.source_execution_url); if (source.childNodes.length) root.append(source);
    const attemptsHeading = document.createElement("h3"); attemptsHeading.textContent = `Attempt history (${data.attempts.length})`; root.append(attemptsHeading); if (!data.attempts.length) { const empty = document.createElement("p"); empty.textContent = "No actual CRM write has been attempted."; root.append(empty); }
    data.attempts.forEach((attempt) => { const item = document.createElement("article"), title = document.createElement("strong"), text = document.createElement("p"); item.className = "attempt"; title.textContent = `Attempt ${attempt.attempt_number}: ${attempt.outcome}`; text.textContent = `Started ${formatTime(attempt.started_at)}; finished ${formatTime(attempt.finished_at)}; HTTP ${attempt.status_code ?? "not recorded"}; error ${attempt.error_class || "none"}; Retry-After ${attempt.retry_after_raw || "not recorded"}${attempt.retry_after_seconds !== null ? ` (${attempt.retry_after_seconds}s)` : ""}.`; item.append(title, text); execution(item, attempt.execution_reference, attempt.execution_url); root.append(item); });
    const incidentsHeading = document.createElement("h3"); incidentsHeading.textContent = `Linked incidents (${data.incidents.length})`; root.append(incidentsHeading); data.incidents.forEach((entry) => root.append(incident(entry)));
  }
  async function detail(jobId) { selectedJob = jobId; const version = ++detailVersion; detailController?.abort(); const controller = detailController = new AbortController(), root = $("job-detail"); root.className = "detail-empty"; root.textContent = `Loading job ${jobId}…`; try { const data = await read(`/api/operations/jobs/${encodeURIComponent(jobId)}`, controller); if (version === detailVersion && selectedJob === jobId) renderDetail(data); } catch (error) { if (version === detailVersion && selectedJob === jobId && error.name !== "AbortError") { root.className = "detail-empty error"; root.textContent = `Selected job is unavailable: ${error.message || "read failed."}`; } } }
  async function incidents() { incidentsController?.abort(); const controller = incidentsController = new AbortController(); $("incidents-status").textContent = "Loading incidents…"; const p = new URLSearchParams({ state: $("incident-state").value, page: String(incidentsPage), page_size: "25" }); try { const data = await read(`/api/operations/incidents?${p}`, controller); if (incidentsController !== controller) return; const list = $("incidents-list"); list.replaceChildren(); if (!data.items.length) { const empty = document.createElement("li"); empty.textContent = "No incidents match this filter."; list.append(empty); } data.items.forEach((entry) => list.append(incident(entry))); $("incidents-status").className = "operations-status"; $("incidents-status").textContent = `Filtered total: ${data.total}. Showing ${data.items.length} on page ${data.page}. Observed ${formatTime(data.observed_at)}.`; $("incidents-page").textContent = `Page ${data.page}`; $("incidents-previous").disabled = data.page <= 1; $("incidents-next").disabled = data.page * data.page_size >= data.total; } catch (error) { if (incidentsController === controller && error.name !== "AbortError") failure($("incidents-status"), "Incidents could not be read.", error); } }
  $("refresh").addEventListener("click", () => { summary(); jobs(); incidents(); }); $("job-filters").addEventListener("submit", (event) => { event.preventDefault(); jobsPage = 1; jobs(); }); $("incident-filters").addEventListener("submit", (event) => { event.preventDefault(); incidentsPage = 1; incidents(); }); $("jobs-previous").addEventListener("click", () => { if (jobsPage > 1) { jobsPage -= 1; jobs(); } }); $("jobs-next").addEventListener("click", () => { jobsPage += 1; jobs(); }); $("incidents-previous").addEventListener("click", () => { if (incidentsPage > 1) { incidentsPage -= 1; incidents(); } }); $("incidents-next").addEventListener("click", () => { incidentsPage += 1; incidents(); });
  summary(); jobs(); incidents();
})();
