import hashlib
import json
import smtplib
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone
from email.message import EmailMessage
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from app.config import settings
from app.models import Appointment, AuditEvent, FollowUp, Lead
from app.schemas.lifecycle import BookingCreate


class BookingConflictError(Exception):
    """A booking request conflicts with existing durable state."""


class BookingValidationError(Exception):
    """A booking uses an unsupported timezone or invalid local time."""


class EmailDeliveryError(Exception):
    """The local development email sink could not accept a message."""


@dataclass(frozen=True)
class BookingResult:
    appointment: Appointment
    follow_up: FollowUp | None
    created: bool


@dataclass(frozen=True)
class DispatchResult:
    state: str
    pipeline_stage: str
    sent_at: datetime | None


class DevelopmentEmailGateway:
    def send(self, recipient: str, subject: str, body: str) -> None:
        message = EmailMessage()
        message["From"] = settings.development_email_from
        message["To"] = recipient
        message["Subject"] = subject
        message.set_content(body)
        try:
            with smtplib.SMTP(settings.smtp_host, settings.smtp_port, timeout=5) as smtp:
                smtp.send_message(message)
        except (OSError, smtplib.SMTPException) as error:
            raise EmailDeliveryError("The local development email sink is unavailable.") from error


def booking_fingerprint(payload: BookingCreate) -> str:
    encoded = json.dumps(
        {
            "correlation_id": str(payload.correlation_id),
            "appointment_local": payload.appointment_local.isoformat(timespec="minutes"),
            "business_timezone": payload.business_timezone,
        },
        sort_keys=True,
        separators=(",", ":"),
    ).encode()
    return hashlib.sha256(encoded).hexdigest()


class LifecycleService:
    def __init__(self, email_gateway: DevelopmentEmailGateway | None = None) -> None:
        self.email_gateway = email_gateway or DevelopmentEmailGateway()

    @staticmethod
    def due_follow_ups(db: Session, limit: int) -> list[FollowUp]:
        now = datetime.now(timezone.utc)
        statement = (
            select(FollowUp)
            .where(FollowUp.status == "pending", FollowUp.due_at <= now)
            .order_by(FollowUp.due_at.asc())
            .limit(limit)
        )
        return list(db.scalars(statement))

    def dispatch_follow_up(self, db: Session, follow_up_id: uuid.UUID) -> DispatchResult:
        lead_id = db.scalar(select(FollowUp.lead_id).where(FollowUp.id == follow_up_id))
        if not lead_id:
            raise LookupError("Follow-up not found")
        lead = db.scalar(select(Lead).where(Lead.id == lead_id).with_for_update())
        follow_up = db.scalar(
            select(FollowUp)
            .where(FollowUp.id == follow_up_id)
            .with_for_update()
            .execution_options(populate_existing=True)
        )
        if not follow_up:
            raise LookupError("Follow-up not found")
        if follow_up.status != "pending":
            return DispatchResult(follow_up.status, lead.pipeline_stage, follow_up.sent_at)
        due_at = follow_up.due_at
        if due_at.tzinfo is None:
            due_at = due_at.replace(tzinfo=timezone.utc)
        if due_at > datetime.now(timezone.utc):
            return DispatchResult("not_due", lead.pipeline_stage, None)
        if not lead.email:
            raise BookingValidationError("An email follow-up requires a lead email address.")

        self.email_gateway.send(
            lead.email,
            "Following up on your service request",
            f"Hello {lead.full_name},\n\n"
            "Thank you for contacting our synthetic home-services demonstration. "
            "This is a development test email generated by the lifecycle workflow.\n\n"
            "Regards,\nAutomation Demonstration",
        )
        sent_at = datetime.now(timezone.utc)
        follow_up.status = "sent"
        follow_up.sent_at = sent_at
        previous_stage = lead.pipeline_stage
        if previous_stage == "new_lead":
            lead.pipeline_stage = "contacted"
        db.add_all(
            [
                AuditEvent(
                    correlation_id=lead.correlation_id,
                    lead_id=lead.id,
                    event_type="follow_up.sent",
                    status="success",
                    metadata_json={
                        "follow_up_id": str(follow_up.id),
                        "sent_at": sent_at.isoformat(),
                    },
                ),
                AuditEvent(
                    correlation_id=lead.correlation_id,
                    lead_id=lead.id,
                    event_type="pipeline.stage_changed",
                    status="success",
                    metadata_json={"from": previous_stage, "to": lead.pipeline_stage},
                ),
            ]
        )
        db.commit()
        return DispatchResult("sent", lead.pipeline_stage, sent_at)

    def create_booking(self, db: Session, payload: BookingCreate) -> BookingResult:
        fingerprint = booking_fingerprint(payload)
        existing = db.scalar(
            select(Appointment).where(Appointment.booking_request_id == payload.booking_request_id)
        )
        if existing:
            return self._existing_booking(db, existing, fingerprint)
        if payload.business_timezone != settings.business_timezone:
            raise BookingValidationError(
                f"business_timezone must be {settings.business_timezone}."
            )
        try:
            business_zone = ZoneInfo(settings.business_timezone)
        except ZoneInfoNotFoundError as error:
            raise BookingValidationError(
                "The configured business timezone is unavailable."
            ) from error

        local_time = payload.appointment_local
        appointment_at = local_time.replace(tzinfo=business_zone).astimezone(timezone.utc)
        round_trip = appointment_at.astimezone(business_zone).replace(tzinfo=None)
        if round_trip != local_time:
            raise BookingValidationError("The selected business-local time does not exist.")
        if appointment_at <= datetime.now(timezone.utc):
            raise BookingValidationError("The appointment must be in the future.")

        lead = db.scalar(
            select(Lead).where(Lead.correlation_id == payload.correlation_id).with_for_update()
        )
        if not lead:
            raise LookupError("Lead not found")
        replay_after_lock = db.scalar(
            select(Appointment).where(Appointment.booking_request_id == payload.booking_request_id)
        )
        if replay_after_lock:
            return self._existing_booking(db, replay_after_lock, fingerprint)
        existing_for_lead = db.scalar(select(Appointment).where(Appointment.lead_id == lead.id))
        if existing_for_lead:
            raise BookingConflictError("The lead already has an active appointment.")

        appointment = Appointment(
            booking_request_id=payload.booking_request_id,
            lead_id=lead.id,
            correlation_id=lead.correlation_id,
            appointment_at=appointment_at,
            business_timezone=settings.business_timezone,
            booking_fingerprint=fingerprint,
        )
        db.add(appointment)
        try:
            db.flush()
        except IntegrityError as error:
            db.rollback()
            replay = db.scalar(
                select(Appointment).where(
                    Appointment.booking_request_id == payload.booking_request_id
                )
            )
            if replay:
                return self._existing_booking(db, replay, fingerprint)
            raise BookingConflictError("The lead already has an active appointment.") from error

        follow_up = db.scalar(
            select(FollowUp).where(FollowUp.lead_id == lead.id).with_for_update()
        )
        previous_stage = lead.pipeline_stage
        lead.pipeline_stage = "appointment_booked"
        now = datetime.now(timezone.utc)
        events = [
            AuditEvent(
                correlation_id=lead.correlation_id,
                lead_id=lead.id,
                event_type="appointment.booked",
                status="success",
                metadata_json={
                    "appointment_id": str(appointment.id),
                    "booking_request_id": str(payload.booking_request_id),
                    "appointment_at": appointment_at.isoformat(),
                    "business_timezone": settings.business_timezone,
                },
            ),
            AuditEvent(
                correlation_id=lead.correlation_id,
                lead_id=lead.id,
                event_type="pipeline.stage_changed",
                status="success",
                metadata_json={"from": previous_stage, "to": "appointment_booked"},
            ),
        ]
        if follow_up and follow_up.status == "pending":
            follow_up.status = "cancelled"
            follow_up.cancelled_at = now
            events.append(
                AuditEvent(
                    correlation_id=lead.correlation_id,
                    lead_id=lead.id,
                    event_type="follow_up.cancelled",
                    status="success",
                    metadata_json={
                        "follow_up_id": str(follow_up.id),
                        "cancelled_at": now.isoformat(),
                        "reason": "appointment_booked",
                    },
                )
            )
        db.add_all(events)
        db.commit()
        db.refresh(appointment)
        if follow_up:
            db.refresh(follow_up)
        return BookingResult(appointment=appointment, follow_up=follow_up, created=True)

    def send_booking_confirmation(
        self, db: Session, appointment_id: uuid.UUID
    ) -> DispatchResult:
        appointment = db.scalar(
            select(Appointment).where(Appointment.id == appointment_id).with_for_update()
        )
        if not appointment:
            raise LookupError("Appointment not found")
        lead = db.get(Lead, appointment.lead_id)
        if appointment.confirmation_sent_at:
            return DispatchResult(
                "already_sent", lead.pipeline_stage, appointment.confirmation_sent_at
            )
        if not lead.email:
            return DispatchResult("skipped_no_email", lead.pipeline_stage, None)

        business_zone = ZoneInfo(appointment.business_timezone)
        appointment_at = appointment.appointment_at
        if appointment_at.tzinfo is None:
            appointment_at = appointment_at.replace(tzinfo=timezone.utc)
        local_time = appointment_at.astimezone(business_zone)
        self.email_gateway.send(
            lead.email,
            "Your appointment is booked",
            f"Hello {lead.full_name},\n\n"
            f"Your synthetic demonstration appointment is booked for "
            f"{local_time.strftime('%A, %B %d, %Y at %I:%M %p')} "
            f"({appointment.business_timezone}).\n\n"
            "This is a development test email; no real service appointment was created.\n\n"
            "Regards,\nAutomation Demonstration",
        )
        sent_at = datetime.now(timezone.utc)
        appointment.confirmation_sent_at = sent_at
        db.add(
            AuditEvent(
                correlation_id=lead.correlation_id,
                lead_id=lead.id,
                event_type="booking_confirmation.sent",
                status="success",
                metadata_json={
                    "appointment_id": str(appointment.id),
                    "sent_at": sent_at.isoformat(),
                },
            )
        )
        db.commit()
        return DispatchResult("sent", lead.pipeline_stage, sent_at)

    @staticmethod
    def _existing_booking(
        db: Session, existing: Appointment, fingerprint: str
    ) -> BookingResult:
        if existing.booking_fingerprint != fingerprint:
            raise BookingConflictError(
                "Booking request identifier is associated with different booking data."
            )
        follow_up = db.scalar(select(FollowUp).where(FollowUp.lead_id == existing.lead_id))
        return BookingResult(appointment=existing, follow_up=follow_up, created=False)
